#!/bin/bash
# ============================================================
# Script: 02_project_setup.sh
# Purpose: Create GCP projects and enable required APIs
# Usage: ./scripts/02_project_setup.sh --env=dev
# ============================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../config/common.env"

# ── Parse arguments ────────────────────────────────────────
ENVIRONMENT=""
BILLING_ACCOUNT=""

for arg in "$@"; do
    case $arg in
        --env=*)     ENVIRONMENT="${arg#*=}" ;;
        --billing=*) BILLING_ACCOUNT="${arg#*=}" ;;
        *) log_warn "Unknown argument: $arg" ;;
    esac
done

# ── Prompt if missing ──────────────────────────────────────
if [ -z "$ENVIRONMENT" ]; then
    echo -e "${YELLOW}Enter environment (dev/prod/shared):${NC}"
    read -r ENVIRONMENT
fi

if [ -z "$BILLING_ACCOUNT" ]; then
    echo -e "${YELLOW}Enter Billing Account ID (format: XXXXXX-XXXXXX-XXXXXX):${NC}"
    echo "(Find at: console.cloud.google.com/billing)"
    read -r BILLING_ACCOUNT
fi

# ── Set project ID and folder ──────────────────────────────
PROJECT_ID="${PROJECT_PREFIX}-${ENVIRONMENT}"
source "${SCRIPT_DIR}/../config/${ENVIRONMENT}.env" 2>/dev/null || true

case $ENVIRONMENT in
    dev)    FOLDER_ID="${DEV_FOLDER_ID:-}" ;;
    prod)   FOLDER_ID="${PROD_FOLDER_ID:-}" ;;
    shared) FOLDER_ID="${SHARED_FOLDER_ID:-}" ;;
    *)      log_error "Invalid environment: ${ENVIRONMENT}" ;;
esac

echo "=================================================="
echo " Enterprise HR RAG Platform - Project Setup"
echo " Environment: ${ENVIRONMENT}"
echo " Project ID:  ${PROJECT_ID}"
echo "=================================================="

# ── Create project ─────────────────────────────────────────
log_step "Creating project: ${PROJECT_ID}"

if gcloud projects describe "${PROJECT_ID}" &>/dev/null; then
    log_warn "Project ${PROJECT_ID} already exists - skipping creation"
else
    if [ -n "${FOLDER_ID:-}" ]; then
        gcloud projects create "${PROJECT_ID}" \
            --name="HR RAG ${ENVIRONMENT}" \
            --folder="${FOLDER_ID}"
    else
        gcloud projects create "${PROJECT_ID}" \
            --name="HR RAG ${ENVIRONMENT}"
        log_warn "No folder ID - project created without folder"
    fi
    log_success "Project created: ${PROJECT_ID}"
fi

# ── Link billing ───────────────────────────────────────────
log_step "Linking billing account"
gcloud billing projects link "${PROJECT_ID}" \
    --billing-account="${BILLING_ACCOUNT}"
log_success "Billing linked: ${BILLING_ACCOUNT}"

# ── Enable APIs ────────────────────────────────────────────
log_step "Enabling required APIs (this takes ~5 minutes...)"

APIS=(
    "run.googleapis.com"
    "aiplatform.googleapis.com"
    "secretmanager.googleapis.com"
    "dataflow.googleapis.com"
    "bigquery.googleapis.com"
    "storage.googleapis.com"
    "spanner.googleapis.com"
    "binaryauthorization.googleapis.com"
    "cloudkms.googleapis.com"
    "dlp.googleapis.com"
    "monitoring.googleapis.com"
    "logging.googleapis.com"
    "cloudbuild.googleapis.com"
    "artifactregistry.googleapis.com"
    "iap.googleapis.com"
    "cloudfunctions.googleapis.com"
    "eventarc.googleapis.com"
    "iam.googleapis.com"
    "compute.googleapis.com"
)

for API in "${APIS[@]}"; do
    if gcloud services list \
        --enabled \
        --project="${PROJECT_ID}" \
        --filter="name:${API}" \
        --format="value(name)" 2>/dev/null | grep -q "${API}"; then
        log_info "${API} already enabled"
    else
        gcloud services enable "${API}" \
            --project="${PROJECT_ID}" \
            --quiet
        log_success "Enabled: ${API}"
    fi
done

# ── Create Artifact Registry ───────────────────────────────
log_step "Creating Artifact Registry"

if gcloud artifacts repositories describe "${REGISTRY_NAME}" \
    --location="${REGISTRY_LOCATION}" \
    --project="${PROJECT_ID}" &>/dev/null; then
    log_warn "Registry ${REGISTRY_NAME} already exists"
else
    gcloud artifacts repositories create "${REGISTRY_NAME}" \
        --repository-format=docker \
        --location="${REGISTRY_LOCATION}" \
        --project="${PROJECT_ID}" \
        --description="HR RAG Platform Docker images"
    log_success "Artifact Registry created: ${REGISTRY_NAME}"
fi

# ── Save project ID ────────────────────────────────────────
log_step "Saving project configuration"
cat >> "${SCRIPT_DIR}/../config/${ENVIRONMENT}.env" << ENVEOF

# Project (auto-generated by 02_project_setup.sh)
export PROJECT_ID="${PROJECT_ID}"
export BILLING_ACCOUNT="${BILLING_ACCOUNT}"
ENVEOF

log_success "Project ID saved to config/${ENVIRONMENT}.env"

# ── Summary ────────────────────────────────────────────────
echo ""
echo "=================================================="
log_success "Project setup complete!"
echo ""
echo "  Project ID: ${PROJECT_ID}"
echo "  APIs Enabled: ${#APIS[@]}"
echo "  Artifact Registry: ${REGISTRY_NAME}"
echo ""
echo "Next step: ./scripts/03_networking.sh --env=${ENVIRONMENT}"
echo "=================================================="
