#!/bin/bash
# ============================================================
# Script: 06_vector_search.sh
# Purpose: Create Vertex AI Vector Search index and endpoint
# Usage: ./scripts/06_vector_search.sh --env=dev
# Note: Index creation takes 20-30 minutes!
# ============================================================
set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../config/common.env"

# ── Parse arguments ────────────────────────────────────────
ENVIRONMENT=""
for arg in "$@"; do
    case $arg in
        --env=*) ENVIRONMENT="${arg#*=}" ;;
    esac
done

if [ -z "$ENVIRONMENT" ]; then
    echo -e "${YELLOW}Enter environment (dev/prod):${NC}"
    read -r ENVIRONMENT
fi

source "${SCRIPT_DIR}/../config/${ENVIRONMENT}.env"

echo "=================================================="
echo " Enterprise HR RAG Platform - Vector Search Setup"
echo " Environment: ${ENVIRONMENT}"
echo " Project: ${PROJECT_ID}"
echo "=================================================="

INDEX_NAME="hr-rag-index"
ENDPOINT_NAME="hr-rag-endpoint"
DEPLOYED_INDEX_ID="hr_rag_deployed_index"

# ── Create initial empty index file ───────────────────────
log_step "Preparing index configuration"

# Create empty initial data file for index
cat > /tmp/index_metadata.json << IDXEOF
{
  "contentsDeltaUri": "gs://${ARTIFACTS_BUCKET}/vector-index/",
  "config": {
    "dimensions": ${VECTOR_DIMENSIONS},
    "approximateNeighborsCount": 10,
    "distanceMeasureType": "${VECTOR_DISTANCE}",
    "algorithm_config": {
      "treeAhConfig": {
        "leafNodeEmbeddingCount": 500,
        "fractionLeafNodesToSearch": 0.05
      }
    }
  },
  "indexUpdateMethod": "STREAM_UPDATE"
}
IDXEOF

# Create empty file in GCS for index initialization
echo '{"id": "init", "embedding": [0.0]}' | \
    gcloud storage cp - \
    "gs://${ARTIFACTS_BUCKET}/vector-index/init.json" \
    --project="${PROJECT_ID}" 2>/dev/null && \
    log_success "Index initialization file created" || \
    log_warn "Could not create init file"

# ── Create Vector Search Index ─────────────────────────────

# Helper: Check if index is ready
check_index_ready() {
    local IDX=$1
    local SHARDS=$(gcloud ai indexes describe "${IDX}" \
        --region="${REGION}" \
        --project="${PROJECT_ID}" \
        --format="value(indexStats.shardsCount)" 2>/dev/null)
    [ -n "${SHARDS}" ] && [ "${SHARDS}" -gt 0 ] 2>/dev/null
}

log_step "Creating Vector Search index (takes 20-30 minutes...)"

# Check if index already exists
EXISTING_INDEX=$(gcloud ai indexes list \
    --region="${REGION}" \
    --project="${PROJECT_ID}" \
    --filter="displayName=${INDEX_NAME}" \
    --format="value(name)" 2>/dev/null | head -1)

if [ -n "${EXISTING_INDEX}" ]; then
    log_warn "Index ${INDEX_NAME} already exists: ${EXISTING_INDEX}"
    INDEX_ID="${EXISTING_INDEX}"
else
    log_info "Creating index (please wait 20-30 minutes)..."

    # Create index config file
    cat > /tmp/index_config.json << IDXEOF
{
  "config": {
    "dimensions": ${VECTOR_DIMENSIONS},
    "approximateNeighborsCount": 10,
    "distanceMeasureType": "${VECTOR_DISTANCE}",
    "algorithm_config": {
      "treeAhConfig": {
        "leafNodeEmbeddingCount": 500,
        "fractionLeafNodesToSearch": 0.05
      }
    }
  },
  "indexUpdateMethod": "STREAM_UPDATE"
}
IDXEOF

    INDEX_ID=$(gcloud ai indexes create \
        --region="${REGION}" \
        --project="${PROJECT_ID}" \
        --display-name="${INDEX_NAME}" \
        --description="HR RAG Platform vector index" \
        --metadata-file=/tmp/index_config.json \
        --format="value(name)" 2>/dev/null)
    rm -f /tmp/index_config.json

    if [ -z "${INDEX_ID}" ]; then
        log_warn "Index creation initiated asynchronously"
        log_warn "Check status: gcloud ai indexes list --region=${REGION} --project=${PROJECT_ID}"
    else
        log_success "Index created: ${INDEX_ID}"
    fi
fi

rm -f /tmp/index_metadata.json

# ── Create Index Endpoint ──────────────────────────────────
log_step "Creating Vector Search endpoint"

EXISTING_ENDPOINT=$(gcloud ai index-endpoints list \
    --region="${REGION}" \
    --project="${PROJECT_ID}" \
    --filter="displayName=${ENDPOINT_NAME}" \
    --format="value(name)" 2>/dev/null | head -1)

if [ -n "${EXISTING_ENDPOINT}" ]; then
    log_warn "Endpoint ${ENDPOINT_NAME} already exists"
    ENDPOINT_ID="${EXISTING_ENDPOINT}"
else
    ENDPOINT_ID=$(gcloud ai index-endpoints create \
        --region="${REGION}" \
        --project="${PROJECT_ID}" \
        --display-name="${ENDPOINT_NAME}" \
        --description="HR RAG Platform vector search endpoint" \
        --format="value(name)" 2>/dev/null)
    log_success "Endpoint created: ${ENDPOINT_ID}"
fi


# Vector Search (auto-generated by 06_vector_search.sh)
export VECTOR_INDEX_ID="${INDEX_ID:-pending}"
export VECTOR_ENDPOINT_ID="${ENDPOINT_ID:-pending}"
export DEPLOYED_INDEX_ID="${DEPLOYED_INDEX_ID}"

echo ""
echo "=================================================="
log_success "Vector Search setup initiated!"
echo ""
echo "  Index: ${INDEX_NAME}"
echo "  Endpoint: ${ENDPOINT_NAME}"
echo ""
echo "⚠️  IMPORTANT: Index creation takes 20-30 minutes!"
echo "   Check status with:"
echo "   gcloud ai indexes list --region=${REGION} --project=${PROJECT_ID}"
echo ""
echo "   Once index is READY, deploy it to endpoint:"
echo "   ./scripts/06b_deploy_index.sh --env=${ENVIRONMENT}"
echo ""
echo "Next step (run after index is ready):"
echo "   ./scripts/07_data_pipeline.sh --env=${ENVIRONMENT}"
echo "=================================================="
